name: cron
on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main  # Ensure this is your correct default branch
  workflow_dispatch:

concurrency:
  group: cron
  cancel-in-progress: true

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ./requirements.txt

      - name: Run Sync
        run: |
          python3 main.py

      - name: Check git status
        run: git status

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
